baseURL = 'https://srirangamuc.github.io/portfolio/'
title = 'Srirangam Umesh Chandra'
theme = 'typo'
relativeURLs = true  # ensures all links are relative
canonifyURLs = true  # ensures all links are absolute and prefixed with baseURL

# Taxonomy & Menu settings
[taxonomies]
tag = 'tags'

[[params.menu]]
name = "Home"
url = "/portfolio/"

[[params.menu]]
name = "Projects"
url = "/portfolio/projects/"

[[params.menu]]
name = "Blog"
url = "/portfolio/posts/"

# Social links
[[params.social]]
name = "github"
url = "https://github.com/srirangamuc"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/srirangam-umesh-chandra"

[[params.social]]
name = "medium"
url = "https://medium.com/@uc3932"
