baseURL = 'https://srirangamuc.github.io/portfolio'
title = 'Srirangam Umesh Chandra'
theme = "typo"

[taxonomies]
tag = 'tags'

[params]
theme = "light"  # or "dark"

# Collection settings
homeCollectionTitle = ''
homeCollection = 'home'

paginationSize = 50
listSummaries = true
listDateFormat = '2 Jan 2006'



# Social media icons
[[params.social]]
name = "github"
url = "https://github.com/srirangamuc"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/srirangam-umesh-chandra"

[[params.social]]
name = "medium"
url = "https://medium.com/@uc3932"


# Menu at the top
[[params.menu]]
name = "Home"
url = "/"

[[params.menu]]
name = "Projects"
url = "/projects"

[[params.menu]]
name = "Blog"
url = "/posts"
